import 'dart:convert';

class Regions {
  List<String> regions = [
    "Seleccione una Region",
    "Cercado de Lima",
    "Ate",
    "Barranco",
    "Breña",
    "Comas",
    "Chorrillos"
        "El Agustino",
    "Jesús María",
    "La Molina",
    "La Victoria",
    "Lince",
    "Magdalena del Mar",
    "Miraflores",
    "Pueblo Libre",
    "Puente Piedra",
    "Rimac",
    "San Isidro",
    "Independencia",
    "San Juan de Miraflores",
    "San Luis",
    "San Martin de Porres",
    "San Miguel",
    "Santiago de Surco",
    "Surquillo",
    "Villa María del Triunfo",
    "San Juan de Lurigancho",
    "Santa Rosa",
    "Los Olivos",
    "San Borja",
    "Villa El Savador",
    "Santa Anita",
    "Cercado Callao",
    "Bellavista",
    "Carmen de la Legua",
    "La Perla",
    "La Punta",
    "Ventanilla",
  ];
}
